#!/usr/bin/with-contenv bash
set -e

vecho () { if [ "${S6_VERBOSITY:-1}" -gt 0 ]; then echo "[$0] $@"; fi; }

VAULT_HOME="${VAULT_HOME:-/vault}";
VAULT_CONFIG_DIR="${VAULT_CONFIG_DIR:-${VAULT_HOME}/config}";
VAULT_DATA_DIR="${VAULT_DATA_DIR:-${VAULT_HOME}/file}";
VAULT_LOGS_DIR="${VAULT_LOGS_DIR:-${VAULT_HOME}/logs}";
VAULT_ROLE="${VAULT_ROLE:-server}";

vecho "Ensure configuration directories exist";
mkdir -p \
    "${VAULT_HOME}" \
    "${VAULT_CONFIG_DIR}" \
    "${VAULT_DATA_DIR}" \
    "${VAULT_LOGS_DIR}" \
    ;

if [ -n "${VAULT_LOCAL_CONFIG}" ];
then
    vecho "Adding local config to ${VAULT_CONFIG_DIR}";
    echo "${VAULT_LOCAL_CONFIG}" \
    > "${VAULT_CONFIG_DIR}/local.${VAULT_CONFLANG:-hcl}";
fi;

_subst () {
    sed \
        -e "s|VAULT_HOME|${VAULT_HOME}|g" \
        -e "s|VAULT_CONFIG_DIR|${VAULT_CONFIG_DIR}|g" \
        -e "s|VAULT_DATA_DIR|${VAULT_DATA_DIR}|g" \
        -e "s|VAULT_LOGS_DIR|${VAULT_LOGS_DIR}|g" \
    $1 > $2;
}

# ensure default conf exists
if [ -z "${VAULT_SKIP_ENSURECONFIG}" ] \
&& [ $(find "${VAULT_CONFIG_DIR}" -type f -iname '*.hcl' -or -iname '*.json' | wc -l) -eq 0 ];
then
    vecho "Setting up default ${VAULT_ROLE} config in ${VAULT_CONFIG_DIR}";
    if [ "${VAULT_ROLE^^}" == "SERVER" ];
    then _subst /defaults/server.hcl "${VAULT_CONFIG_DIR}/server.hcl";
    elif [ "${VAULT_ROLE^^}" == "AGENT" ];
    then _subst /defaults/agent.hcl "${VAULT_CONFIG_DIR}/agent.hcl";
    elif [ "${VAULT_ROLE^^}" == "PROXY" ];
    then _subst /defaults/proxy.hcl "${VAULT_CONFIG_DIR}/proxy.hcl";
    fi;
fi;

# fix permissions
if [ -z "${VAULT_SKIP_PERMFIX}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing permissions.";
    chown -R ${S6_USER:-alpine}:${PGID:-1000} \
        "${VAULT_HOME}" \
        "${VAULT_CONFIG_DIR}" \
        "${VAULT_DATA_DIR}" \
        "${VAULT_LOGS_DIR}" \
        ;
fi;

if [ -z "${VAULT_SKIP_SETCAP}" ] \
&& [ "X${EUID}" == "X0" ]; # requires root
then
    vecho "Fixing capabilities.";
    /usr/sbin/setcap CAP_IPC_LOCK=+ep $(readlink -f $(which vault));
fi;

